service-properties:
  service-name: "backoffice-service"

external-services:

spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:h2:mem:db_backoffice-service
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
