apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service-app
  template:
    metadata:
      labels:
        app: customer-service-app
    spec:
      containers:
        - name: customer-service-container
          image: europe-west1-docker.pkg.dev/private-gcp-409308/quickstart-docker-repo/customer-service-image
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: customer-service-k8service
spec:
  selector:
    app: customer-service-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort
