service-properties:
  service-name: "order-service"

external-services:
  checkout-service:
    base-url: http://checkout-service-k8service:8082

spring:
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:h2:mem:db_order-service
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8084

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
