<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="microserviceMetamodell" nsURI="http://microservice.com/microserviceMetamodell"
    nsPrefix="microserviceMetamodell">
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethod">
    <eLiterals name="GET"/>
    <eLiterals name="POST" literal="POST"/>
    <eLiterals name="DELETE"/>
    <eLiterals name="PUT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainmodellayer" eType="#//DomainModelLayer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="technicallayer" upperBound="-1"
        eType="#//TechnicalLayer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructurelayer" upperBound="-1"
        eType="#//InfrastructureLayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainevent" upperBound="-1"
        eType="#//DomainEvent" eOpposite="#//DomainEvent/domainmodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedcontextrelationship"
        lowerBound="1" eType="#//BoundedContext" eOpposite="#//BoundedContext/domainmodel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModelLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedcontext" upperBound="-1"
        eType="#//BoundedContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="microservice" upperBound="-1"
        eType="#//Microservice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//ModelElement #//Factorizeable #//AggregateNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueobject" upperBound="-1"
        eType="#//ValueObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviours" upperBound="-1"
        eType="#//Behaviour" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueObject" eSuperTypes="#//ModelElement #//Factorizeable #//AggregateNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueobject" upperBound="-1"
        eType="#//ValueObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//ModelElement #//Factorizeable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviours" upperBound="-1"
        eType="#//Behaviour" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregate" eSuperTypes="#//Factorizeable #//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregateroot" lowerBound="1"
        eType="#//AggregateRoot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factory" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviours" upperBound="-1"
        eType="#//Behaviour" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryFor" lowerBound="1"
        eType="#//Factorizeable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//ModelElement #//Factorizeable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" upperBound="-1"
        eType="#//Behaviour" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" eType="#//Aggregate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainmodel" lowerBound="1"
        eType="#//DomainModel" eOpposite="#//DomainModel/domainevent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedcontextrelationship"
        upperBound="-1" eType="#//BoundedContextRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainmodel" eType="#//DomainModel"
        eOpposite="#//DomainModel/boundedcontextrelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootEntity" lowerBound="1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviourName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedKernel" eSuperTypes="#//BoundedContextRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomerSupplier" eSuperTypes="#//UpstreamDownstreamRelationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conformist" eSuperTypes="#//DownstreamRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnticorruptionLayer" eSuperTypes="#//DownstreamRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenHostService" eSuperTypes="#//UpstreamRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublishedLanguage" eSuperTypes="#//UpstreamRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedContextRelationship" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="#//Interface"
        eOpposite="#//Interface/boundedcontextrelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpstreamRole" abstract="true" eSuperTypes="#//RelationshipRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="DownstreamRole" abstract="true" eSuperTypes="#//RelationshipRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipRole" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpstreamDownstreamRelationship" abstract="true"
      eSuperTypes="#//BoundedContextRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="downstream" eType="#//RelationshipRole"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upstream" eType="#//RelationshipRole"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelementimplementation"
        eType="#//ModelElementImplementation" eOpposite="#//ModelElementImplementation/modelelement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factorizeable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateNode" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatenode" upperBound="-1"
        eType="#//AggregateNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Microservice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelementimplementation"
        upperBound="-1" eType="#//ModelElementImplementation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workflowRole" eType="#//WorkflowRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelementimplementation"
        eType="#//ModelElementImplementation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainevent" eType="#//DomainEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedcontextrelationship"
        eType="#//BoundedContextRelationship" eOpposite="#//BoundedContextRelationship/interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynchronousInterface" eSuperTypes="#//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="restEndpoints" upperBound="-1"
        eType="#//RestEndpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsynchronousInterface" eSuperTypes="#//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceRole" eType="#//AsynchronousInterfaceRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topologyType" eType="#//TopologyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestEndpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpMethod" eType="#//HttpMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementImplementation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" eType="#//ModelElement"
        eOpposite="#//ModelElement/modelelementimplementation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AsynchronousInterfaceRole">
    <eLiterals name="PRODUCER"/>
    <eLiterals name="CONSUMER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TopologyType">
    <eLiterals name="BROKER"/>
    <eLiterals name="MEDIATOR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkflowRole">
    <eLiterals name="ORCHESTRATOR"/>
    <eLiterals name="ORCHESTRATED" value="1"/>
    <eLiterals name="CHOREOGRAPH" value="2"/>
  </eClassifiers>
</ecore:EPackage>
