/**
 */
package microserviceMetamodell.provider;

import java.util.ArrayList;
import java.util.Collection;

import microserviceMetamodell.util.MicroserviceMetamodellAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MicroserviceMetamodellItemProviderAdapterFactory extends MicroserviceMetamodellAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MicroserviceMetamodellItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.DomainObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainObjectItemProvider domainObjectItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.DomainObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainObjectAdapter() {
		if (domainObjectItemProvider == null) {
			domainObjectItemProvider = new DomainObjectItemProvider(this);
		}

		return domainObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.DomainObjectController} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainObjectControllerItemProvider domainObjectControllerItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.DomainObjectController}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainObjectControllerAdapter() {
		if (domainObjectControllerItemProvider == null) {
			domainObjectControllerItemProvider = new DomainObjectControllerItemProvider(this);
		}

		return domainObjectControllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.RestEndpoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestEndpointItemProvider restEndpointItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.RestEndpoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRestEndpointAdapter() {
		if (restEndpointItemProvider == null) {
			restEndpointItemProvider = new RestEndpointItemProvider(this);
		}

		return restEndpointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.DomainObjectService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainObjectServiceItemProvider domainObjectServiceItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.DomainObjectService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainObjectServiceAdapter() {
		if (domainObjectServiceItemProvider == null) {
			domainObjectServiceItemProvider = new DomainObjectServiceItemProvider(this);
		}

		return domainObjectServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.DomainObjectRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainObjectRepositoryItemProvider domainObjectRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.DomainObjectRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainObjectRepositoryAdapter() {
		if (domainObjectRepositoryItemProvider == null) {
			domainObjectRepositoryItemProvider = new DomainObjectRepositoryItemProvider(this);
		}

		return domainObjectRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.SystemModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemModelItemProvider systemModelItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.SystemModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemModelAdapter() {
		if (systemModelItemProvider == null) {
			systemModelItemProvider = new SystemModelItemProvider(this);
		}

		return systemModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link microserviceMetamodell.DomainWebservice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainWebserviceItemProvider domainWebserviceItemProvider;

	/**
	 * This creates an adapter for a {@link microserviceMetamodell.DomainWebservice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainWebserviceAdapter() {
		if (domainWebserviceItemProvider == null) {
			domainWebserviceItemProvider = new DomainWebserviceItemProvider(this);
		}

		return domainWebserviceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (domainObjectItemProvider != null) domainObjectItemProvider.dispose();
		if (domainObjectControllerItemProvider != null) domainObjectControllerItemProvider.dispose();
		if (restEndpointItemProvider != null) restEndpointItemProvider.dispose();
		if (domainObjectServiceItemProvider != null) domainObjectServiceItemProvider.dispose();
		if (domainObjectRepositoryItemProvider != null) domainObjectRepositoryItemProvider.dispose();
		if (systemModelItemProvider != null) systemModelItemProvider.dispose();
		if (domainWebserviceItemProvider != null) domainWebserviceItemProvider.dispose();
	}

}
