spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: yourGroupId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/yourdb
    username: root
    password: secret
