apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-service-app
  template:
    metadata:
      labels:
        app: backoffice-service-app
    spec:
      containers:
        - name: backoffice-service-container
          image: europe-west1-docker.pkg.dev/private-gcp-409308/quickstart-docker-repo/backoffice-service-image
          ports:
            - containerPort: 8081

---
kind: Service
apiVersion: v1
metadata:
  name: backoffice-service-k8service
spec:
  selector:
    app: backoffice-service-app
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30001
  type: NodePort
