apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service-app
  template:
    metadata:
      labels:
        app: checkout-service-app
    spec:
      containers:
        - name: checkout-service-container
          image: europe-west1-docker.pkg.dev/private-gcp-409308/quickstart-docker-repo/checkout-service-image
          ports:
            - containerPort: 8082

---
kind: Service
apiVersion: v1
metadata:
  name: checkout-service-k8service
spec:
  selector:
    app: checkout-service-app
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 30002
  type: NodePort
