#

pluginName = microserviceMetamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_DomainObject_type = Domain Object
_UI_DomainObjectController_type = Domain Object Controller
_UI_RestEndpoint_type = Rest Endpoint
_UI_DomainObjectService_type = Domain Object Service
_UI_DomainObjectRepository_type = Domain Object Repository
_UI_SystemModel_type = System Model
_UI_DomainWebservice_type = Domain Webservice
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_DomainObject_objectName_feature = Object Name
_UI_DomainObject_domainObjectRepository_feature = Domain Object Repository
_UI_DomainObject_domainObjectService_feature = Domain Object Service
_UI_DomainObject_domainObjectController_feature = Domain Object Controller
_UI_DomainObjectController_restEndpoints_feature = Rest Endpoints
_UI_DomainObjectController_objectName_feature = Object Name
_UI_DomainObjectController_domainObjectServices_feature = Domain Object Services
_UI_RestEndpoint_httpMethod_feature = Http Method
_UI_RestEndpoint_path_feature = Path
_UI_DomainObjectService_objectName_feature = Object Name
_UI_DomainObjectService_domainObjectRepositories_feature = Domain Object Repositories
_UI_DomainObjectService_calls_feature = Calls
_UI_DomainObjectRepository_objectName_feature = Object Name
_UI_SystemModel_webservices_feature = Webservices
_UI_SystemModel_description_feature = Description
_UI_DomainWebservice_domainObjectControllers_feature = Domain Object Controllers
_UI_DomainWebservice_domainObjectServices_feature = Domain Object Services
_UI_DomainWebservice_domainObjectRepositories_feature = Domain Object Repositories
_UI_DomainWebservice_domainName_feature = Domain Name
_UI_DomainWebservice_domainObjects_feature = Domain Objects
_UI_DomainWebservice_hostUrl_feature = Host Url
_UI_Unknown_feature = Unspecified

_UI_HttpMethod_GET_literal = GET
_UI_HttpMethod_POST_literal = POST
_UI_HttpMethod_DELETE_literal = DELETE
